Tracking inventory
amymhaddad/exercises_for_programmers_2019 pull request #5
Opened 2019-05-29 19:08 UTC by amymhaddad

Adding track_inventory project for PR review. This project gets inventory information from user and creates a tabular table.

2019-06-05 18:41 UTC, amymhaddad commented
@paulghaddad This project is updated. Pls review these files:
main.py
create_inventory_tracking_report.py 
inventory_item.py
inventory_tracking_management.py
inventory_report.py

2019-06-08 18:43 UTC, paulghaddad requested changes
Awesome work! 💯

2019-06-08 18:43 UTC, paulghaddad commented on track_inventory/create_inventory_tracking_report.py
> +"""Get user input and create an inventory report"""
Nice module name.

2019-06-08 18:43 UTC, paulghaddad commented on track_inventory/create_inventory_tracking_report.py
> +def get_inventory_report_name():
Good function.

2019-06-08 18:43 UTC, paulghaddad commented on track_inventory/inventory_tracking_management.py
> +"""Write report inventory to a json or csv file"""
Excellent; nice functions here and this module only contains items related to outputting to a file.

2019-06-08 18:43 UTC, paulghaddad commented on track_inventory/main.py
> +def main(filename):
Nice work. This `main` function is well-organized into input -> core -> output.

2019-06-08 18:43 UTC, paulghaddad commented on track_inventory/inventory_report.py
> +class InventoryReport:
Perfect class all around!

2019-06-08 18:43 UTC, paulghaddad commented on track_inventory/inventory_item.py
> +class InventoryItem:
👏

2019-06-10 17:21 UTC, merged